[variables]
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"
VIRTUAL_ENV = "/opt/venv"
PATH = "/opt/venv/bin:$PATH"

[phases.setup]
nixPkgs = ["python311", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "virtualenv /opt/venv",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
